name: Build data & Deploy to Pages
on:
  schedule: [{ cron: '0 1 * * *' }]   # 01:00 UTC = 09:00 Taipei
  workflow_dispatch:
  push: { branches: [main] }

permissions: { contents: read, pages: write, id-token: write }
concurrency: { group: pages, cancel-in-progress: true }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate data via Alpha Vantage
        env: { AV_KEY: ${{ secrets.Alpha_Vantage_KEY }} }
        run: |
          set -e
          mkdir -p data
          SYMS=$(test -f symbols.txt && cat symbols.txt || echo "TSLA NVDA TSM")
          for s in $SYMS; do
            echo "Fetch $s"
            for i in 1 2 3; do
              curl -s "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=${s}&outputsize=compact&apikey=${AV_KEY}" > "data/${s}.json"
              if jq -e 'has("Time Series (Daily)")' "data/${s}.json" >/dev/null; then
                echo "OK: $s"; break
              else
                echo "Not ready (rate limit?). attempt=$i/3"; sleep 65
              fi
            done
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: { path: . }

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: { name: github-pages, url: ${{ steps.deployment.outputs.page_url }} }
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
